
POST http://localhost:8080/login
Content-Type: application/json

{
"username":"Talos",
"email":"geormarga@gmail.com",
"password":"123456aA!"
}

###
POST http://localhost:8080/game
Content-Type: application/json

{
"command":"start game"
}